### ISSUE TITLE
Stripe not working through solidus_gateway.

### ISSUE THREAD

**Issue by Homeshchopra94** [solidusio/solidus_gateway#17]
when i am trying to use stripe  through solidus_gateway i am getting a token issue because i am getting gateway_payment_profile_id as string instead of an object.
![fg](https://cloud.githubusercontent.com/assets/17905033/14876709/aebb579c-0d34-11e6-8d59-a42112ba8ea2.png)

**Comment by ridem** [comment]
I'm having the same issue here

**Comment by Senjai** [comment]
@ridem Aye, the version was relaxed, this should be fixed on master.
