### ISSUE TITLE
Amazon payments

### ISSUE THREAD

**Issue by RoverWire** [solidusio/solidus_gateway#29]
is there any guide to enable/use amazon payment? already try to use `solidus_amazon_payments` but not sure if is that required for `solidus_gateway`, since the amazon option is not displayed on the checkout.

**Comment by Senjai** [comment]
https://github.com/solidusio/solidus_gateway/tree/master/spec/models/gateway are the only gateways solidus_gateway supports. We'd accept pull requests for additional ones if there is already an active merchant integration for it.

solidus_amazon_payments sounds like another extension, you'll have to ask there if you're having problems with it.

**Comment by RoverWire** [comment]
But seems like only adding `solidus_gateway` is not enough to make amazon payments works, that is the reason of my question here.
