### ISSUE TITLE
Missing existing_payment views

### ISSUE THREAD

**Issue by brchristian** [solidusio/solidus_gateway#48]
The Solidus commit https://github.com/solidusio/solidus/pull/1707/files added a partials folder called `existing_payment`, but there are no such views in the `master` branch of `solidus_gateway`.

This means that users using Stripe and Quick Checkout will cause 500 errors when they try to check out.

This is a show-stopping issue, as it literally breaks checkout in some Stores.

What we need: views in the `spree/checkout/existing_payment/` path for Stripe and Quick Checkout. I’m not sure what these views are supposed to look like exactly, so I’m not sure what the PR would be here. But this is an urgent issue for anyone using Solidus 2.2 and Stripe or Quick Checkout in production.

**Comment by tvdeyen** [comment]
Fixed by #49
