### ISSUE TITLE
Incomplete list of gateways in admin

### ISSUE THREAD

**Issue by ignaciosm** [solidusio/solidus_gateway#53]
Hi,
I've noticed that the list in the admin doesn't show all the gateways available in ActiveMerchant. For example: PayuLatam appears as available in ActiveMerchant but not in Solidus Gateway. Is there a way to add it? 
https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/payu_latam.rb

Thanks!

**Comment by tvdeyen** [comment]
This gem never meant to be a complete implementation of all gateways activemerchant provides. The name is confusing. Actually this gem provides payment methods for Solidus where some of them use a active merchant gateway as the way to talk to a providers API. 

Nevertheless, yes it is possible to add new payment methods. Please have a look into one of the payment methods provided in this gem and adopt accordingly.
