### ISSUE TITLE
dependency added two times

### ISSUE THREAD

**Issue by ccarruitero** [solidusio/solidus_gateway#68]
Since last commit `ffaker` was added in [Gemfile](https://github.com/solidusio/solidus_gateway/blob/master/Gemfile#L15) and in [gemspec](https://github.com/solidusio/solidus_gateway/blob/master/solidus_gateway.gemspec#L44). And I think is enough to be in one place.

I prefer to add in Gemfile since this is just necessary to avoid an error  when run tests and isn't used for the gem itself.

What do you think? @tvdeyen @swcraig

**Comment by tvdeyen** [comment]
Oh. An oversight on my side. This should be changed. Thanks for reporting. 

Actually I don’t care where we put this. As long as we use `add_development_dependency` (what we do) it can stay in the gemspec http://guides.rubygems.org/specification-reference/#add_development_dependency

**Comment by swcraig** [comment]
This was my mistake to not notice that it had been added to the Gemfile. Thanks @ccarruitero.
This has been reverted in #69.

**Comment by ccarruitero** [comment]
@tvdeyen @swcraig thanks for your comments.

I close, since [this](https://github.com/solidusio/solidus_gateway/commit/076dc735c3e55b380ba3e3bb4ce522ab006b030d) fix the problem
