### ISSUE TITLE
BeansteamGateway loading

### ISSUE THREAD

**Issue by jtapia** [solidusio/solidus_gateway#73]
```
/app/models/spree/gateway/beanstream.rb:77:in `<class:Beanstream>': uninitialized constant ActiveMerchant::Billing::BeanstreamGateway (NameError)
```

**Comment by askl56** [comment]
@jtapia what was your solution to this?

**Comment by jtapia** [comment]
if I remember well I included `require "activemerchant"` on `solidus_gateway.rb` before `require "solidus_gateway/engine"`

**Comment by ccarruitero** [comment]
This was fixed by https://github.com/solidusio/solidus_gateway/commit/47dc9fc749a42fe0bb197fee7b267ec2436129b0

So, I think we can close.

**Comment by jtapia** [comment]
👍
